SELECT P.ID   AS P_ID,        --PROOF ID
  E.ID       AS E_ID,        --ENTRY ID
  CITY.COMP_ID    AS WITHHOLD_ID, --統編
  U.CODE          AS EMP_ID,      --所得人證號
  DECODE(U.ID,NULL,INU.IDENTITY_ID,U.IDENTITY_ID)  AS TAX_ID,
  DECODE(U.ID,NULL,INU.NAME,U.NAME)     AS TAX_NAME,
  ACC.INCOME_FORM           AS INCOME_FORM ,        --所得格式
  CASE  WHEN ACC.CODE='63300205' THEN N'G3'
        WHEN ACC.CODE='63300105' THEN N'G2'--'
  ELSE   ACC.INCOME_FORM END    AS SOURCE_KIND,         --所得來源類別
  SUB.SUBPOENA_NO           AS PAY_CERT_NO,         --付款憑單編號
  SUB.SUBPOENA_NO           AS SUBPOENA_NO ,        --傳票號碼
  SUB.SUBPOENA_DATE         AS SUBPOENA_DATE ,      --傳票日期
  ACC.INCOME_BIZ             AS TAXBIZ_CODE ,        --業別代號
  G.GAIN_AMT                 AS CROSS_INCOME ,       --給付總額
  ACC.TAX_RATE                AS TAX_RATE ,           --稅率
  G.TAX_AMT2                 AS WITHHOLDING_TAX ,    --稅額
  APPLD.CODE                 AS COST_UNIT_CODE ,     --分錄成本單位代號
  APPLD.NAME                AS COST_UNIT_NAME ,     --分錄成本單位中文
  '1'                         AS TEX_REMIT ,          --稅金匯回
  R.ROSTER_NO               AS ROSTER_NO,           --名冊單號
  'GROUP_ID'                  AS GROUP_ID,            --分錄群組ID
  'TBEXP_ENTRY_TAX_ID'         AS TBEXP_ENTRY_TAX_ID , --所得稅分錄
  ' F225942034'                 AS CREATE_USER_ID ,     --建檔人員
  '2011-06-13'                  AS CREATE_DATE ,        --建檔日
  '1'                           AS VERSION_NO           --版本
FROM TBEXP_EXPAPPL_B B
INNER JOIN TBEXP_PROOF P ON P.TBEXP_EXPAPPL_B_ID=B.ID
INNER JOIN TBEXP_PROOF_ENTRY_R ER ON ER.TBEXP_PROOF_ID=P.ID
INNER JOIN TBEXP_ENTRY E ON E.ID=ER.TBEXP_ENTRY_ID
INNER JOIN TBEXP_ROSTER_DETAIL R ON R.ID=P.TBEXP_ROSTER_DETAIL_ID
INNER JOIN TBEXP_ACC_TITLE ACC ON ACC.ID=E.TBEXP_ACC_TITLE_ID
INNER JOIN TBEXP_USER APPL ON APPL.ID=B.TBEXP_APPL_USER_ID
INNER JOIN TBEXP_DEPARTMENT APPLD ON APPLD.ID=APPL.TBEXP_DEPARTMENT_ID
INNER JOIN TBEXP_AREA AREA ON AREA.ZIP = APPLD.ZIP
INNER JOIN TBEXP_CITY CITY ON CITY.ID = AREA.TBEXP_CITY_ID
INNER JOIN TBEXP_GAIN_PERSON G ON G.TBEXP_ROSTER_DETAIL_ID=R.ID
LEFT JOIN TBEXP_USER U ON U.CODE=G.GAIN_USER_ID
LEFT JOIN TBEXP_INCOME_USER　INU ON INU.ID=G.TBEXP_INCOME_USER_ID
INNER JOIN TBEXP_SUBPOENA SUB ON SUB.ID        =B.TBEXP_SUBPOENA_ID
WHERE ACC.CODE LIKE '6%'
AND  R.ROSTER_NO='AD5000120140515001';




select*from tbexp_expappl_c c 
inner join tbexp_entry e on e.tbexp_entry_group_id=c.tbexp_entry_group_id
inner join tbexp_subpoena s on s.id=c.tbexp_subpoena_id
inner join TBEXP_ROSTER_DETAIL rt on rt.exp_appl_no=c.exp_appl_no
where s.subpoena_no in ('S016C22002')


--新增語法
Insert into EXPADMIN.TBEXP_TAX_DETAIL
   (ID, WITHHOLD_ID, EMP_ID, TAX_ID, TAX_NAME, INCOME_FORM, SOURCE_KIND, PAY_CERT_NO,SUBPOENA_NO, SUBPOENA_DATE, TAXBIZ_CODE, CROSS_INCOME, TAX_RATE, WITHHOLDING_TAX, COST_UNIT_CODE, COST_UNIT_NAME, TEX_REMIT,ROSTER_NO, GROUP_ID, TBEXP_ENTRY_TAX_ID, CREATE_USER_ID, CREATE_DATE, VERSION_NO  )
    Values
   ('201403-00000000-000J0020140123002005', '43643658', 'S46990', 'H227523879', '林○惠', '91','91', 'S003528001','S003528001', TO_DATE('2014-02-05','YYYY-MM-DD'), '', '3000', '0.1', '0', 'AKD000', '新桃通－收', '1','AD5000120140515001', 'IMP00000-0000-0000-J0020140123002001', '', 'F225942034', TO_DATE('2014-02-05','YYYY-MM-DD'), '1');

INSERT INTO TBEXP_PROOF_TAX_DETAIL_R (TBEXP_TAX_DETAIL_ID,TBEXP_PROOF_ID)
Values('201403-00000000-000J0020140124002005','201403-00000000-000J0020140124002005');

INSERT INTO TBEXP_ENTRY_EXP_GROUP(ID, GROUP_ID,TBEXP_ENTRY_ID)
VALUES ('IMP00310-0000-0000-S0232050020000007','IMP00000-0000-0000-J0020140123002007','3C1834F9-250F-4EFA-9357-AAE0F5DF6A32');

--B
select * from tbexp_expappl_b b
inner join tbexp_entry e on e.tbexp_entry_group_id=b.tbexp_entry_group_id
inner join tbexp_proof_entry_r per on per.tbexp_entry_id=e.id
inner join tbexp_proof p on p.id=per.tbexp_proof_id
where p.tbexp_expappl_b_id is null AND B.EXP_APPL_NO='510201801080005'